language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "codewinger-github"
    token:
      secure: "5570782c8970758d55333fb6c5912080076816b9"

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'